# Generated by Django 3.2.9 on 2022-02-02 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0003_auto_20220202_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollers',
        ),
        migrations.AddField(
            model_name='course',
            name='enrollers',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='program',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='program',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
