# Generated by Django 3.2.9 on 2022-02-03 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0004_auto_20220202_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrollers',
            field=models.ManyToManyField(blank=True, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
